### PR TITLE
Add support xenial without RHEL support

### PR DESCRIPTION
**Pull request by chr4**

### CODE REVIEW

**Comment by chr4** [comment]
@Dens49 how did you rund the rspec suite? I'm getting errors that it can't find the Berksfile...

**Comment by Dens49** [comment]
@chr4 Moved to the directory of default_spec.rb and used:
`chef exec rspec default_spec.rb`

**Comment by chr4** [comment]
Thanks, that worked!

**Comment by chr4** [comment]
Merged this into master along with the other changes and documentation updates.
Will release `2.2.0` after I made a few more tests on my machines. 

Feel free to test current master as well, and publish results here!

**Pull request merged**
