### PR TITLE
Mark password as not required

### LINKED ISSUE #1: Required argument password is missing
I'm trying to use this cookbook with Vagrant, but I can't get it to allow the MySQL user `root` to have no password. I added `cookbook "mysqld"` to my `Cheffile`, and the following to my `Vagrantfile`:

```
config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "mysqld"
end
```

But when I do `vagrant up`, the Chef configuration fails. Here is the relevant output:

```
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/82891d35d286774d89cfbe3b7a9ea9d4/cookbooks/mysqld/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: Chef::Exceptions::ValidationFailed
==> default: ----------------------------------
==> default: Required argument password is missing!
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/82891d35d286774d89cfbe3b7a9ea9d4/cookbooks/mysqld/recipes/configure.rb:26:in `block in from_file'
==> default: 
==> default:   /tmp/vagrant-chef/82891d35d286774d89cfbe3b7a9ea9d4/cookbooks/mysqld/recipes/configure.rb:25:in `from_file'
==> default: 
==> default:   /tmp/vagrant-chef/82891d35d286774d89cfbe3b7a9ea9d4/cookbooks/mysqld/recipes/default.rb:22:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/82891d35d286774d89cfbe3b7a9ea9d4/cookbooks/mysqld/recipes/configure.rb:
==> default: 
==> default:  19:  #
==> default:  20:  
==> default:  21:  # Configure mysql/mariadb according to attributes
==> default:  22:  mysqld 'default'
==> default:  23:  
==> default:  24:  # Set password according to attribute, if set
==> default:  25:  mysqld_password 'root' do
==> default:  26>>   password node['mysqld']['root_password']
==> default:  27:    only_if { node['mysqld']['root_password'] }
==> default:  28:  end
==> default:  29:  
==> default:  30:  # Set debian-sys-maint password on Debian family
==> default:  31:  mysqld_password 'debian-sys-maint' do
==> default:  32:    password node['mysqld']['root_password']
==> default:  33:    only_if { node['mysqld']['root_password'] && node['platform_family'] == 'debian' }
==> default:  34:  end
==> default:  35:  
==> default: 
==> default: [2015-03-26T21:29:12+00:00] ERROR: Running exception handlers
==> default: [2015-03-26T21:29:12+00:00] ERROR: Exception handlers complete
==> default: [2015-03-26T21:29:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-03-26T21:29:12+00:00] ERROR: Required argument password is missing!
```

The documentation mentions that the root password will be set **if given**, so I don't see why the argument is required.

Any thoughts?

### PR DESCRIPTION
**Pull request by 501st-alpha1**
I'm not familiar enough with Chef to know if this is the correct way to do this, or if it is more of a hack. If it is the latter, let me know and I will try to figure out a better way to do it.
Fixes #1.

### CODE REVIEW

**Comment by chr4** [comment]
Hi, thank your for your contribution! That's the clean way to not make an attribute mandatory.
Did you run the tests using `kitchen` to make sure nothing breaks?
I'll look into this a bit later.

**Comment by 501st-alpha1** [comment]
Cool, glad to hear it.

I can't seem to figure out how to run the tests. Is there supposed to be a `.kitchen.yml` file in the repo?

**Comment by chr4** [comment]
My bad. There's only some specs for this repository.
I'll merge this, as I don't believe this is going to hurt anyone. :)

**Comment by chr4** [comment]
Released in v1.0.1
Thanks again!

**Pull request merged**
